name: Check Code Formatting

on:
    # Run on PRs to ensure the code is safe to merge
    pull_request:

    # Only run on push if it is to the main branch (post-merge)
    push:
        branches:
            - main

jobs:
    clang-format-checking:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: RafikFarhad/clang-format-github-action@v3
              with:
                  sources: "**/*.hpp,**/*.cpp,**/*.c,**/*.h"
